# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swapserverrpc/common.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "swapserverrpc/common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aswapserverrpc/common.proto\x12\x07looprpc"\x82\x01\n\x07HopHint\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63han_id\x18\x02 \x01(\x04\x12\x15\n\rfee_base_msat\x18\x03 \x01(\r\x12#\n\x1b\x66\x65\x65_proportional_millionths\x18\x04 \x01(\r\x12\x19\n\x11\x63ltv_expiry_delta\x18\x05 \x01(\r"0\n\tRouteHint\x12#\n\thop_hints\x18\x01 \x03(\x0b\x32\x10.looprpc.HopHintB-Z+github.com/lightninglabs/loop/swapserverrpcb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "swapserverrpc.common_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z+github.com/lightninglabs/loop/swapserverrpc"
    )
    _globals["_HOPHINT"]._serialized_start = 40
    _globals["_HOPHINT"]._serialized_end = 170
    _globals["_ROUTEHINT"]._serialized_start = 172
    _globals["_ROUTEHINT"]._serialized_end = 220
# @@protoc_insertion_point(module_scope)
